interfaces: ['eth0']
config:
  subnets:
  - start: 172.22.0.0
    netmask: 255.255.255.0
      mac: 00:01:02:aa:bb:cc
      ip: 172.22.0.3
config:
  groups:
  - domainName: example.com
    domainNameServers: [172.22.0.1]
    routers: [172.22.0.1]
    subnetMask: 255.255.255.0
    hosts:
    - name: c1
      mac: 00:01:02:aa:bb:cc
      ip: 172.22.0.3